### ISSUE TITLE
Public API unavailable

### ISSUE THREAD

**Issue by sedubois** [graphcool/graphql-weather-api#3]
The README mentions this should be available at https://api.graph.cool/relay/v1/weather, but that page yields `Project not found` (for `requestId` `citsfp3fm0g8m012464dilduz`). Will that be fixed or is this repo deprecated? If so, could that be indicated in README?

It could be quite handy to have a public API to experiment, especially to provide in boilerplate projects. It could also be linked from landing page for people to discover (similar to what dgraph.io does).

I think a kittens Instagram API like in your tutorial could be pretty cool 😄

**Comment by sorenbs** [comment]
Hi Sedubois :-)

This is an old experiment that is not currently maintained. I'll make the repo private to not confuse people. We will be introducing a series of integrations over the coming months and I don't see why a weather api shouldn't be one of them. You can help us prioritise as soon as we have the new feature voting platform in place.
